### ISSUE TITLE
Accounts section grayed out

### ISSUE THREAD

**Issue by ancapbarbie** [aaroncox/vessel#103]
After clicking "Create account" the entire Accounts section is grayed out and unresponsive. This persists after reloading under the "View" menu and after system reboot.

Ubuntu 18.04

**Comment by fraenk** [comment]
Yeap... encountered the same problem after clicking "create account"

most likely due to the deprecated create_account_with_delegation stuff that was dropped with HF20 and vessel not being able to do the necessary requests for account creation costs?!

the only way I found to get the account screen back into working condition was by deleting the local storage and then re-importing my PKs to vessel.

for Windows: close Vessel, navigate to `\Users\username\AppData\Roaming\vessel\Local Storage` and delete all files within. Then restart Vessel in "blank" condition and add your accounts anew.

**Comment by ancapbarbie** [comment]
Yes! Pressing [ESC] worked. Thank you!

**Comment by fraenk** [comment]
lol... ok... that's a lot easier than deleting the local storage and starting from scratch...
