### ISSUE TITLE
Attempting to create new account fails with error message 'Insufficient Delegation'.

### ISSUE THREAD

**Issue by Mustard5** [aaroncox/vessel#40]
I've tried creating an account several times.  My account has 203 liquid steem at the time of account creation attempt.  I can't understand what the issue is.

current_delegation >= target_delegation: Inssufficient Delegation 61759.461351 VESTS required, 61759.461350 VESTS provided. account_creation_fee=0.200 STEEM o.fee=0.200 STEEM o.delegation=59700.812639 VESTS

**Comment by aaroncox** [comment]
61759.461351 VESTS required
61759.461350 VESTS provided

This happens occasionally and is a bug in dsteem, and happens because the amount of VESTS required slowly increases over time. If you wait too long on the final screen, this can happen. 

That explains why, but we'll have to come up with a fix for it.

**Comment by Mustard5** [comment]
Thanks for the reply.

When I attempted to create the account, I was in a power down.  Today I stopped the power down and was able to successfully create a new account.

**Comment by fraenk** [comment]
Hi @aaroncox, I doubt that this is the same issue but to avoid opening a new one I'll just add to this thread.

Upon clicking "Create Account" the translucent blocking layer gets activated and the account screen becomes unusable. The console shows a timeout error.

Even after restarting Vessel the blocking layer persists and I have to manually clear the storage and reimport the account to get the wallet working again.
