### ISSUE TITLE
Strange behaviour when delegating to a user who has already some delegation

### ISSUE THREAD

**Issue by prcolaco** [aaroncox/vessel#46]
I wanted to delegate twice more power from one user to another that I had already delegated to. The UI didn't let me know what would happen and only let's me delegate the amount that is available, but then it changes the amount delegated as if it was editing the delegation.
Then I thought that I could achieve what I wanted by delegating a minimum amount and then delegating the maximum amount afterwards, but it turned out that I stayed with the power locked and only a fraction of what I wanted was delegated.
The 7 day restriction applies also when raising the delegation? It shouldn't I think... Maybe the slider should allow to take from the current value to the maximum (available+already delegated) instead?
Anyway it could be important to have some information on the UI that would explain this case for users...

**Comment by aaroncox** [comment]
You're absolutely right - the UI is pretty terrible for altering delegations to an account you've already delegated. 

I'm going to mark this for the next version since I think it's a priority. Basically whatever you set the value to is what it will be. There's no adding/subtracting, it just sets a value, and the UI should reflect that.

**Comment by aaroncox** [comment]
Got this fixed by adding an "edit" button to existing delegations that also includes SP that's already delegated between the two accounts. Will be released in 0.0.9.
